git add .\assets\css\admin.css
git add .\assets\img\conoceles.jpg
git add .\assets\img\consulta.png
git add .\assets\img\pp\.
git add .\assets\video\.
git add .\comm\.
git add .\css\.
git add .\ejecutar.bat
git add .\estadisticas\.
git add .\gets\.
git add .\index.htmlBAK
git add .\index.php
git add .\index_n.php
git add .\index_nuevo.php
git add .\js\estadisticas\.
git add .\js\home\.
git add .\js\main_overall.js
git add .\js\obten_datos.js
git add .\js\perfiles\.
git add .\layout\.
git add .\libs\highlight\highlight-github.css
git add .\libs\highlight\highlight-github.css.map
git add .\pages\acceso_denegado.php
git add .\pages\administradores.php
git add .\pages\areas_ite.php
git add .\pages\ayuntamientos.php
git add .\pages\candidatos.php
git add .\pages\cargos_ite.php
git add .\pages\componentes\aviso_priv.php
git add .\pages\componentes\edad.php
git add .\pages\componentes\password_copy.js
git add .\pages\componentes\password_gen.js
git add .\pages\construccion.php
git add .\pages\construccion_index.php
git add .\pages\crud_administrador.php
git add .\pages\crud_areas_ite.php
git add .\pages\crud_cand_ayun.php
git add .\pages\crud_cand_dip_mr.php
git add .\pages\crud_cand_dip_rp.php
git add .\pages\crud_cargos_ite.php
git add .\pages\crud_verificador.php
git add .\pages\diputados_mr.php
git add .\pages\diputados_rp.php
git add .\pages\password_edit_admin.php
git add .\pages\password_edit_ayun.php
git add .\pages\password_edit_dip_mr.php
git add .\pages\password_edit_dip_pr.php
git add .\pages\password_edit_dip_rp.php
git add .\pages\password_edit_veri.php
git add .\pages\plantillas\.
git add .\pages\verificadores.php
git add .\perfiles\.
git add .\posts\.
git add .\public\.